# Generated by Django 5.0.1 on 2024-02-08 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('abstract', models.TextField()),
                ('authors', models.SlugField(max_length=500)),
                ('adviser', models.SlugField(max_length=250)),
                ('panels', models.SlugField(max_length=500)),
                ('status', models.CharField(choices=[('APP', 'Approved'), ('PEN', 'Pending'), ('REJ', 'Rejected')], default='PEN', max_length=3)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('the_one_who_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='thesis_post_publish_27fe8d_idx')],
            },
        ),
    ]
