# Generated by Django 5.0.1 on 2024-02-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='adviser',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='panels',
            field=models.CharField(max_length=500),
        ),
    ]
