# Generated by Django 5.0.1 on 2024-03-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_alter_post_slug_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=3),
        ),
    ]
